config/routes.rb
Rails.application.routes.draw do

  root 'high_voltage/pages#show', id: 'index'
  get 'index-responsive', to: 'application#index'
  resources :contacts, only: [:new, :create]
  resources :subscriptions, only: [:new, :create]
  get :livestream, to: redirect('https://new.livestream.com/tedx/recife')

end

app/models/subscription.rb
require 'valid_email'

class Subscription < ActiveRecord::Base
  validates :name, :email, :cpf, :birthday, :message, presence: true
  validates :email, email: true, if: :email_changed?
  validates :cpf, cpf: true, if: :cpf_changed?
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  def index
    render 'pages/index-responsive'
  end
end

app/controllers/contacts_controller.rb
class ContactsController < ApplicationController
  respond_to :js

  def new
    @contact = Contact.new
  end

  def create
    @contact = Contact.new(params[:contact])
    @contact.request = request

    if @contact.valid?
      @contact.deliver
      flash[:success] = 'Obrigado pela sua mensagem, responderemos em breve. :)'
    end
  end
end

app/controllers/subscriptions_controller.rb
class SubscriptionsController < ApplicationController
  def new
    @subscription = Subscription.new
  end

  def create
    @subscription = Subscription.new(subscription_params)

    if @subscription.save
      flash[:success] = 'Obrigado pelo interesse, responderemos em breve. :)'
    end
  end

  private

  def subscription_params
    params.require(:subscription).
      permit(:name, :email, :cpf, :birthday, :corporation, :message, :social_networks)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def speakers
    return @speakers if @speakers

    file = YAML.load_file('config/speakers.yml')
    @speakers = file.fetch('speakers')
  end

  def talks
    return @talks if @talks

    file = YAML.load_file('config/talks.yml')
    @talks = file.fetch('talks')
  end
end

app/views/contacts/_form.html.erb
<%= form_for contact, remote: true, html: { class: 'contact-form clearfix', novalidate: browser.mobile? || browser.tablet? ? true : false } do |f| %>
  <ul>
    <% f.object.errors.full_messages.each do |message| %>
      <li><%= message %></li>
    <% end %>
  </ul>

  <fieldset>
    <div class="form-group">
      <%= f.label :name, "Nome" %>
      <%= f.text_field :name, required: true, class: 'input form-control' %>
    </div>

    <div class="form-group">
      <%= f.label :email, "Email" %>
      <%= f.email_field :email, required: true,class: 'input form-control' %>
    </div>

    <div class="form-group">
      <%= f.label :message, "Mensagem" %>
      <%= f.text_area :message, rows: 4, required: true, class: 'input form-control' %>
    </div>
  </fieldset>

  <fieldset class="buttons">
    <%= f.button "Enviar", class: 'btn-submit btn pull-right' %>
  </fieldset>
<% end %>

app/views/contacts/create.js.erb
<% if @contact.errors.empty? %>
  message = "<%= j render 'shared/success_message', message: flash[:success] %>";
  $('.contact-form').replaceWith(message);
<% else %>
  form = "<%= j render 'form', contact: @contact %>";
  $('.contact-form').replaceWith(form);
<% end %>

app/views/contacts/new.js.erb
form = "<%= j render 'form', contact: @contact %>";
$('.contact-body .press').before(form);

app/views/layouts/application.html.erb
<!DOCTYPE html>
<!--[if lt IE 7]>      <html class="no-js lt-ie9 lt-ie8 lt-ie7"> <![endif]-->
<!--[if IE 7]>         <html class="no-js lt-ie9 lt-ie8"> <![endif]-->
<!--[if IE 8]>         <html class="no-js lt-ie9"> <![endif]-->
<!--[if gt IE 8]><!--> <html class="no-js"> <!--<![endif]-->
<head>
  <meta charset="utf-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
  <title>TEDx Recife 2014 – Revoluções Silenciosas <%= yield(:page_title) %></title>
  <meta name="description" content="Com o tema Revoluções Silenciosas, o TEDxRecife 2014 objetiva identificar as atitudes e mudanças que tem sua gênese no indivíduo, muitas vezes pequenas ações silenciosas e pessoais que quando percebidas por outros ao redor têm potência para transformar a cidade e a sociedade. ">
  <meta name="keywords" content="ted, tedx, recife, revoluções, silenciosas, 2014, TEDxRecife, cidade, sociedade, indivíduo">
  <meta name="robot" content="index,nofollow">
  <meta name="revisit-after" CONTENT="3">

  <meta name="viewport" content="width=device-width">

  <meta property="og:title" content="TEDx Recife 2014 – Revoluções Silenciosas">
  <meta property=”og:type” content="website"/>
  <meta property="og:image" content="<%= asset_url 'tedx-recife-2014-logo.png' %>">
  <meta property="og:description" content="Com o tema Revoluções Silenciosas, o TEDxRecife 2014 objetiva identificar as atitudes e mudanças que tem sua gênese no indivíduo, muitas vezes pequenas ações silenciosas e pessoais que quando percebidas por outros ao redor têm potência para transformar a cidade e a sociedade.">
  <meta property="og:url" content="<%= root_url %>">

  <meta name=”twitter:card” content="summary">
  <meta name=”twitter:url” content="<%= root_path %>">
  <meta name=”twitter:title” content="TEDx Recife 2014 – Revoluções Silenciosas">
  <meta name=”twitter:description” content="Com o tema Revoluções Silenciosas, o TEDxRecife 2014 objetiva identificar as atitudes e mudanças que tem sua gênese no indivíduo, muitas vezes pequenas ações silenciosas e pessoais que quando percebidas por outros ao redor têm potência para transformar a cidade e a sociedade.">
  <meta name=”twitter:image” content="<%= asset_url 'tedx-recife-2014-logo.png'%>">

  <meta property="place:location:latitude" content="-8.140798">
  <meta property="place:location:longitude" content="-34.904638">

  <%= stylesheet_link_tag "https://netdna.bootstrapcdn.com/font-awesome/4.1.0/css/font-awesome.min.css", cache: true %>
  <%= stylesheet_link_tag    'application', media: 'all' %>
  <%= javascript_include_tag :modernizr %>
  <%= csrf_meta_tags %>
</head>
<body class="<%= yield(:body_classes) %>">
  <div class="hide" itemscope itemtype="http://data-vocabulary.org/Event">
    <a href="" itemprop="url" >
      <span itemprop="summary">TEDx Recife 2014 &ndash; Revolu&ccedil;&otilde;es Silenciosas</span>
    </a>
    <img itemprop="photo" src="<%= asset_url 'tedx-recife-2014-logo.png' %>" />

    <span itemprop="description">Com o tema Revolu&ccedil;&otilde;es Silenciosas, o TEDxRecife 2014 objetiva identificar as atitudes e mudan&ccedil;as que tem sua g&ecirc;nese no indiv&iacute;duo, muitas vezes pequenas a&ccedil;&otilde;es silenciosas e pessoais que quando percebidas por outros ao redor t&ecirc;m pot&ecirc;ncia para transformar a cidade e a sociedade.</span>

    When:
    <time itemprop="startDate" datetime="2014-12-16T15:00-03:00">Dec 16, 3:00PM</time>—
    <time itemprop="endDate" datetime="2014-12-16T22:00-03:00">Dec 16, 10:00PM</time>

    Where:
    <span itemprop="location" itemscope itemtype="http://data-vocabulary.org/Organization">
      <span itemprop="name">Parque Dona Lindu</span>
      <span itemprop="address" itemscope itemtype="http://data-vocabulary.org/Address">
        <span itemprop="street-address">Av. Boa Viagem</span>,
        <span itemprop="locality">Recife</span>,
        <span itemprop="region">Pernambuco</span>
      </span>
      <span itemprop="geo" itemscope itemtype="http://data-vocabulary.org/Geo">
        <meta itemprop="latitude" content="-8.140798" />
        <meta itemprop="longitude" content="-34.904638" />
      </span>
    </span>

    Category: <span itemprop="eventType">Conference</span>
  </div>

  <%= render 'shared/global_nav' %>
  <%= yield %>

  <%= javascript_include_tag 'application' %>
  <% if content_for :additional_js %>
    <%= yield(:additional_js) %>
  <% end %>

  <script>
    (function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
    (i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
    m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
    })(window,document,'script','//www.google-analytics.com/analytics.js','ga');

    ga('create', 'UA-55296435-1', 'auto');
    ga('send', 'pageview');
  </script>
</body>
</html>

app/views/pages/_modern_index.html.erb
<%= content_for :navbar_unresponsive do %>
  true
<% end %>
<%= content_for :additional_js do %>
  <script>
    impress().init();

    $(document).ready(function(){
      $(".pie").peity("pie")
      new OpeningAnimation('.menu').animate()

      $(document).on('impress:stepenter', function(event){
        $backButton = $('.back-button')

        if ($(event.target).prop('id') == $('#main-section').prop('id')) {
          $backButton.fadeOut()
        } else {
          $backButton.fadeIn()
        }
      });
    })
  </script>
<% end %>

<div id="impress">
  <section  id="main-section" class="step main-section clearfix" data-x="0" data-y="0">
    <div class="menu">
      <h2 class="menu-title">Conceito 2014</h2>
      <svg class="main-ball"></svg>
      <p class="menu-hint">passe o mouse ou navegue pelas setas do teclado</p>
    </div>
    <%= render 'pages/concept/animation' %>
    <%= render 'pages/executor/animation' %>
    <%= render 'pages/contact/animation' %>
    <%= render 'pages/subscription/animation' %>
    <h1 class="banner">TEDx Recife 2014 – Revoluções Silenciosas</h1>
  </section>
  <%= render 'pages/concept/body', hide: true %>
  <%= render 'pages/executor/body', hide: true %>
  <%= render 'pages/contact/body', hide: true %>
  <%= render 'pages/subscription/body', hide: true %>
</div>
<%= link_to "Voltar", '#main-section', class: 'back-button' %>

app/views/pages/_responsive_index.html.erb
<div class="container index-responsive">
  <div class="row">
    <div class="col-md-12">
      <div class="col-md-12">
        <h1 class="main-header">TEDx Recife 2014 – Revoluções Silenciosas</h1>
      </div>
      <ul class="list-unstyled big-day-links">
        <li>
          <%= link_to page_path('talks'), class: 'talks-link' do %>
            <i class="fa fa-users"></i>
            Confira os palestrantes deste ano
          <% end %>
        </li>
        <li>
          <%= link_to livestream_path, class: 'livestream-link', target: :blank do %>
            <i class="fa fa-video-camera"></i>
            <span class="call">Assista em Livestream!</span>
          <% end %>
        </li>
      </ul>


      <%= render 'pages/concept/body' %>
      <%= render 'pages/subscription/body' %>
      <%= render 'pages/executor/body' %>
      <%= render 'pages/contact/body' %>
      <div class="col-md-12 clearfix">
        <ul class="list-inline ted-logos">
          <li class="ted-logo">
            <%= link_to 'TED', page_path('about-ted') %>
          </li>
          <li class="tedx-logo">
            <%= link_to 'TEDx', page_path('about-tedx') %>
          </li>
        </ul>
      </div>
    </div>
  </div>
</div>

app/views/pages/_videos_mosaic.html.erb
<section class="video-list clearfix hidden-sm hidden-xs">
  <% speaker = speakers['belize-camara'] %>
  <div class="video-list-item belize-camara col-md-7" style="height: 350px; margin-top: 102px;" data-href="<%= speaker['video'] %>">
    <div class="overlay">
      <div class="header">
        <h4 class="talk" style="font-size: 2em;"><%= speaker['talk'] %></h4>
        <h5 class="speaker" style="font-size: 1.3em;"><%= speaker['name'] %></h5>
      </div>
      <p class="description"><%= speaker['description'] %></p>
    </div>
  </div>
  <% speaker = speakers['guilherme-jordao'] %>
  <div class="video-list-item guilherme-jordao col-md-5" style="height: 202px; margin-top: 50px;" data-href="<%= speaker['video'] %>">
    <div class="overlay">
      <div class="header">
        <h4 class="talk" style="font-size: 1.2em;"><%= speaker['talk'] %></h4>
        <h5 class="speaker" style="font-size: 1.1em;"><%= speaker['name'] %></h5>
      </div>
      <p class="description" style="font-size: 0.9em;"><%= speaker['description'] %></p>
    </div>
  </div>
  <% speaker = speakers['pedro-melo'] %>
  <div class="video-list-item pedro-melo col-md-5" style="height: 202px;" data-href="<%= speaker['video'] %>">
    <div class="overlay">
      <div class="header">
        <h4 class="talk" style="font-size: 1.2em;"><%= speaker['talk'] %></h4>
        <h5 class="speaker" style="font-size: 1.2em;"><%= speaker['name'] %></h5>
      </div>
      <p class="description" style="font-size: 0.9em;"><%= speaker['description'] %></p>
    </div>
  </div>
  <% speaker = speakers['gustavo-maia'] %>
  <div class="video-list-item gustavo-maia col-md-3" style="height: 300px;margin-left: 50px;" data-href="<%= speaker['video'] %>">
    <div class="overlay">
      <div class="header">
        <h4 class="talk" style="font-size: 1.3em;"><%= speaker['talk'] %></h4>
        <h5 class="speaker" style="font-size: 1.1em;"><%= speaker['name'] %></h5>
      </div>
      <p class="description" style="font-size: 0.9em;"><%= speaker['description'] %></p>
    </div>
  </div>
  <% speaker = speakers['flavia-moura'] %>
  <div class="video-list-item flavia-moura col-md-4" style="height: 300px;" data-href="<%= speaker['video'] %>">
    <div class="overlay">
      <div class="header">
        <h4 class="talk" style="font-size: 1.8em;"><%= speaker['talk'] %></h4>
        <h5 class="speaker" style="font-size: 1.2em;"><%= speaker['name'] %></h5>
      </div>
      <p class="description" style="font-size: .9em;"><%= speaker['description'] %></p>
    </div>
  </div>
  <% speaker = speakers['rafa-mattos'] %>
  <div class="video-list-item rafa-mattos col-md-4" style="height: 230px;" data-href="<%= speaker['video'] %>">
    <div class="overlay">
      <div class="header">
        <h4 class="talk" style="font-size: 1.4em;"><%= speaker['talk'] %></h4>
        <h5 class="speaker" style="font-size: 1.1em;"><%= speaker['name'] %></h5>
      </div>
      <p class="description" style="font-size: .9em; margin-top: -4px;"><%= speaker['description'] %></p>
    </div>
  </div>
  <% speaker = speakers['andrea-souza'] %>
  <div class="video-list-item andrea-souza col-md-4" style="height: 180px;" data-href="<%= speaker['video'] %>">
    <div class="overlay">
      <div class="header">
        <h4 class="talk" style="font-size: 1.2em;"><%= speaker['talk'] %></h4>
        <h5 class="speaker" style="font-size: 1.1em;"><%= speaker['name'] %></h5>
      </div>
      <p class="description" style="font-size: 0.9em;"><%= speaker['description'] %></p>
    </div>
  </div>
  <% speaker = speakers['renato-kyiama'] %>
  <div class="video-list-item renato-kyiama col-md-5" style="height: 225px; float: right;" data-href="<%= speaker['video'] %>">
    <div class="overlay">
      <div class="header">
        <h4 class="talk" style="font-size: 1.3em;"><%= speaker['talk'] %></h4>
        <h5 class="speaker" style="font-size: 1.1em;"><%= speaker['name'] %></h5>
      </div>
      <p class="description" style="font-size: .74em;"><%= speaker['description'] %></p>
    </div>
  </div>
  <% speaker = speakers['leonardo-cisneiros'] %>
  <div class="video-list-item leonardo-cisneiros col-md-6 col-md-offset-1" style="height: 325px; margin-top: -100px;" data-href="<%= speaker['video'] %>">
    <div class="overlay">
      <div class="header">
        <h4 class="talk" style="font-size: 1.3em;"><%= speaker['talk'] %></h4>
        <h5 class="speaker" style="font-size: 1.1em;"><%= speaker['name'] %></h5>
      </div>
      <p class="description"><%= speaker['description'] %></p>
    </div>
  </div>
</section>

app/views/pages/about-ted.html.erb
<%= content_for :page_title, ' – Sobre o TED' %>

<% content_for :body_classes do %>
  dark-body about-ted
<% end %>

<div class="container">
  <div class="row">
    <div class="col-md-12">
      <section class="main">
        <h2>Sobre o <strong class="big-ted-logo">TED</strong></h2>

        <p>O <strong>TED</strong> surgiu em 1984 e já teve entre seus palestrantes Bill Clinton, Paul Simon, Bill Gates, Bono Vox, Al Gore, Michelle Obama e Philippe Starck.</p>

        <div class="embed-responsive embed-responsive-4by3">
          <iframe src="//player.vimeo.com/video/7871511" class="embed-responsive-item" webkitallowfullscreen mozallowfullscreen allowfullscreen></iframe>
        </div>

        <p>Imagine poder viajar, por alguns minutos, pelo cérebro dos maiores pensadores do mundo.</p>

        <p>Essa é a proposta do <strong>TED</strong>, que surgiu em 1984 como uma conferência anual na Califórnia sobre tecnologia, entretenimento e design. Daí o nome.</p>

        <p>Já compartilharam suas idéias, no palco do evento, ícones de diferentes áreas como Bill Clinton, Paul Simon, Bill Gates, Bono Vox, Al Gore, Michelle Obama e Philippe Starck.</p>

        <p>Apesar dos mil lugares disponíveis na plateia, as inscrições para as palestras, com duração máxima de 18 minutos cada, esgotam-se um ano antes. Aqueles que não conseguem um ingresso assistem no site, que já conta com mais de 50 milhões de acessos, em 150 países.</p>

        <p>A cada ano a organização elege um pensador de destaque e repassa 100 mil dólares para que ele possa realizar “Um Desejo que Vai Mudar o Mundo”. E, com as 4 ações, TED Conference, TED Talks, TED Prize e TEDx, o mote “ideias que merecem ser espalhadas” vai ganhando vida.</p>

        <p>"Acreditamos apaixonadamente no poder das ideias para mudar atitudes, vidas e, em última instância, o mundo", dizem os organizadores do <strong>TED</strong>.</p>

        <p><strong>Nós também. E você?</strong></p>
      </section>

      <%= render 'shared/symbol' %>
    </div>
  </div>
</div>

app/views/pages/about-tedx-recife.html.erb
<%= content_for :page_title, ' – Sobre o TEDx Recife 2013' %>

<% content_for :body_classes do %>
  dark-body about-tedx-recife
<% end %>

<div class="container">
  <div class="row">
    <div class="col-md-12">
      <section class="main">
        <h2>Sobre o <strong class="tedx-recife-2013-logo">TEDx Recife 2013</strong></h2>

        <p>O <strong>TEDxRecife2013</strong> foi um evento sem ﬁns lucrativos, que reuniu 11 pensadores e realizadores das mais diversas áreas do conhecimento, como artes, tecnologia, ciência e empreendedorismo. Personagens que tiveram um papel ativo na construção da história do Recife compartilharam suas melhores ideias e experiências em palestras com duração entre 06 e 18 minutos, impulsionando discussões, reﬂexões e conexões de alcance local, regional e global.</p>

        <p>O <strong>TEDxRecife</strong> foi realizado no dia 30 de novembro de 2013, no Teatro Santa Isabel, e foi transmitido ao vivo para o mundo todo! Com o tema: “Rompendo Ideias com Ideais”, 11 palestrantes compartilharam com o público suas ideias que estão revolucionando a forma que vivemos, convivemos, trabalhamos e aprendemos.</p>
      </section>

      <%= render 'pages/videos_mosaic' %>

      <ul class="list-unstyled video-list-minified hidden-md hidden-lg">
        <% speakers.each do |(_, infos)| %>
          <li class="video-list-minified-item" data-href="<%= infos['video'] %>">
            <div class="details">
              <%= link_to infos['video'], target: :blank, class: 'video-link' do %>
                <h4 class="talk">
                  <%= infos['talk'] %>
                  <i class="fa fa-youtube-play"></i>
                </h4>
              <% end %>
              <h5 class="speaker"><%= infos['name'] %></h5>
              <%= image_tag "speakers/responsive/#{infos['photo']}", class: 'img-responsive photo' %>
              <p class="description"><%= infos['description'] %></p>
            </div>
          </li>
        <% end %>
      </ul>

      <%= render 'shared/symbol' %>
    </div>
  </div>
</div>

app/views/pages/about-tedx.html.erb
<%= content_for :page_title, ' – Sobre o TEDx' %>

<% content_for :body_classes do %>
  dark-body about-tedx
<% end %>

<div class="container">
  <div class="row">
    <div class="col-md-12">
      <section class="main">
        <h2>Sobre o <strong class="big-tedx-logo">TEDx</strong></h2>

        <p><strong>TEDx</strong> é um programa de eventos locais, auto-organizados que juntam pessoas para compartilhar uma experiência no estilo <strong>TED</strong>.</p>

        <div class="embed-responsive embed-responsive-4by3">
          <iframe src="//www.youtube.com/embed/N-l1xtCMnpw?rel=0" frameborder="0" allowfullscreen></iframe>
        </div>

        <p>Dar asas às grandes idéias para levá-las aos quatro cantos do mundo. Com esse objetivo, foi criado o <strong>TEDx</strong>. Um programa de eventos locais, organizado de forma independente, que reúne pessoas para compartilhar uma experiência no estilo <strong>TED</strong>.</p>

        <p>No <strong>TEDxRecife</strong>, vídeos de palestras (TEDTalks) e palestrantes ao vivo serão combinados para impulsionar conexões e discussões que terão alcance em nível local, regional e global.</p>

        <p>A <strong>TED Conference</strong> fornece guias gerais para o programa <strong>TEDx</strong>, mas estes eventos são organizados por um time de profissionais dedicados, não envolvendo o <strong>TED</strong>.</p>
      </section>

      <%= render 'shared/symbol' %>
    </div>
  </div>
</div>

app/views/pages/concept/_animation.html.erb
<div class="concept clearfix">
  <ul class="first-column">
    <li class="little-ball first-ball">
      <span class="pie" data-fill='["#9D2016", "#FD1D07"]'>4,7</span>
    </li>
    <li class="little-ball">
      <span class="pie" data-fill='["#9D2016", "#FD1D07"]'>1/2</span>
    </li>
    <li class="little-ball last-ball">
      <span class="pie" data-fill='["#FD1D07", "#F9E5E4", "#9D2016"]'>3.6,1.4,5</span>
    </li>
  </ul>
  <ul class="middle-column">
    <li class="little-ball first-ball">
      <span class="pie" data-fill='["#F9E5E4", "#FF2B06", "#9E2515", "#F95E4E"]'>3.5,2.5,1.5,2.5</span>
    </li>
    <li class="little-ball">
      <span class="pie" data-fill='["#FEBBB4"]'>1</span>
    </li>
    <li class="little-ball third-ball">
      <span class="pie" data-fill='["#F75A4E", "#FD1D07"]'>3/4</span>
    </li>
    <li class="little-ball last-ball">
      <span class="pie last-ball" data-fill='["#FEBBB4"]'>10</span>
    </li>
  </ul>
  <ul class="last-column">
    <li class="little-ball last-ball">
      <span class="pie" data-fill='["#F9E5E4", "#9D2016", "#FD1D07"]'>1.5,7,1.5</span>
    </li>
  </ul>
  <svg class="dots-net"></svg>
</div>

app/views/pages/contact/_animation.html.erb
<div class="contact clearfix">
  <ul class="single-column middle">
    <li class="little-ball last-ball">
      <span class="pie" data-fill='["#9D2016", "#F9E5E4"]'>1/2</span>
    </li>
  </ul>
  <ul class="single-column last">
    <li class="little-ball last-ball">
      <span class="pie" data-fill='["#9D2016", "#F9E5E4"]'>1/2</span>
    </li>
  </ul>
  <ul class="middle-column">
    <li class="little-ball first-ball">
      <span class="pie" data-fill='["#F9E5E4", "#FD1D07", "#9D2016"]'>5,2.5,2.5</span>
    </li>
    <li class="little-ball">
      <span class="pie" data-fill='[ "#FD1D07", "#9D2016"]'>1/2</span>
    </li>
    <li class="little-ball last-ball">
      <span class="pie last-ball" data-fill='[ "#FD1D07",  "#9D2016"]'>4,6</span>
    </li>
  </ul>
  <ul class="first-column">
    <li class="little-ball first-ball">
      <span class="pie" data-fill='["#F75A4E", "#FD1D07"]'>4,6</span>
    </li>
    <li class="little-ball last-ball">
      <span class="pie" data-fill='["#FEBBB4"]'>1</span>
    </li>
  </ul>
  <svg class="dots-net"></svg>
</div>

app/views/pages/index.html.erb
<% if browser.mobile? || browser.tablet? %>
  <%= render 'pages/responsive_index' %>
<% else %>
  <%= render 'pages/modern_index' %>
<% end %>

app/views/shared/_global_nav.html.erb
<% responsive = true %>

<% if content_for :navbar_unresponsive %>
  <% responsive = !(yield :navbar_unresponsive) %>
<% end %>

<% if responsive %>
  <nav class="global-nav navbar navbar-inverse" role="navigation">
    <div class="container-fluid">
      <div class="navbar-header">
        <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar-collapse">
          <span class="sr-only">Toggle navigation</span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
        </button>
      </div>

      <div class="hidden-xs">
        <%= render 'shared/nav_menu' %>
      </div>

      <div class="collapse navbar-collapse" id="navbar-collapse">
        <ul class="nav navbar-nav visible-xs-block">
          <li>
            <%= link_to 'TED', page_path('about-ted') %>
          </li>
          <li>
            <%= link_to 'Palestrantes', page_path('talks') %>
          </li>
          <li>
            <%= link_to 'Assista em LIVESTREAM', livestream_path,  target: :blank %>
          </li>
          <li>
            <%= link_to 'TEDx', page_path('about-tedx') %>
          </li>
          <li>
            <%= link_to 'TEDx Recife 2013', page_path('about-tedx-recife') %>
          </li>
        </ul>
      </div>
    </div>
  </nav>
<% else %>
  <nav class="global-nav" role="navigation">
    <%= render 'shared/nav_menu' %>
  </nav>
<% end %>

app/views/shared/_nav_menu.html.erb
<ul class="global-nav-list clearfix nav navbar-nav">
  <li class="global-nav-item ted-logo">
    <%= link_to 'TED', page_path('about-ted') %>
  </li>
  <li class="global-nav-item talks-logo">
    <%= link_to 'Palestrantes', page_path('talks') %>
  </li>
  <li class="global-nav-item livestream-logo">
    <%= link_to 'Assista e LIVESTREAM', livestream_path, target: :blank %>
  </li>
  <li class="global-nav-item tedx-logo">
    <%= link_to 'TEDx', page_path('about-tedx') %>
  </li>
  <li class="global-nav-item tedx-recife-logo">
    <%= link_to 'TEDx Recife', page_path('about-tedx-recife') %>
  </li>
</ul>

app/views/shared/_success_message.html.erb
<%= content_tag :div, class: 'success-message clearfix' do %>
  <%= content_tag :strong, message, class: 'message' %>
<% end %>

app/views/shared/_symbol.html.erb
<h1 class="symbol"><%= link_to 'TEDx Recife 2014', root_path %></h1>